queue:
  name: Hosted VS2017

steps:
- script: 'dotnet tool install -g Wyam.Tool'

- script: 'wyam -i wwwroot'
  failOnStderr: true
  displayName: 'Generate website with Wyam'
  env:
    SKIP_WYAM_API_GEN: '0'

# Copy Files
- task: CopyFiles@2
  inputs:
    displayName: 'Copy output to Artifacts'
    sourceFolder: '$(Build.SourcesDirectory)\output'
    contents: '**\*'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Wyam output'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
  condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], false))
